name: Build Windows Binary
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install msys2
        uses: msys2/setup-msys2@v2
        with:
          packages: 'mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake'

      - name: Add staging repo
        shell: msys2 {0}
        run: |
          cp /etc/pacman.conf /etc/pacman.conf.bak
          grep -qFx '[staging]' /etc/pacman.conf || sed -i '/^# \[staging\]/,/^$/ s|^# ||g' /etc/pacman.conf

      - name: Install OpenSSL and zlib with MSYS2
        run: |
          msys2 -c 'pacman -Syu --noconfirm'
          msys2 -c 'pacman -S --noconfirm mingw-w64-x86_64-openssl mingw-w64-x86_64-zlib'
          msys2 -c 'pacman -S --noconfirm mingw-w64-x86_64-libunix++'

      - run: |
          make
  
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: unpacker.exe
          path: unpacker.exe
