name: Build Windows Binary
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v2
  
     - name: Install MSYS2
       uses: msys2/setup-msys2@v2
       with:
         msystem: MINGW64
         update: true
         install: >-
           mingw-w64-x86_64-gcc
           mingw-w64-x86_64-cmake
           mingw-w64-x86_64-make
           mingw-w64-x86_64-openssl
           mingw-w64-x86_64-zlib
  
     - name: Add MSYS2 to PATH
       run: echo "::add-path::C:\msys64\mingw64\bin"
  
     - name: Build with Makefile
       run: mingw32-make
  
     - name: Upload binary
       uses: actions/upload-artifact@v3
       with:
         name: unpacker.exe
         path: unpacker.exe
