name: Build Windows Binary
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install msys2
        uses: msys2/setup-msys2@v2

      - name: Install OpenSSL and zlib with MSYS2
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm mingw-w64-x86_64-openssl mingw-w64-x86_64-zlib
  
      - name: Install Unix++ (if available via MSYS2)
        run: |
          pacman -S --noconfirm mingw-w64-x86_64-libunix++

      - run: |
          make
  
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: unpacker.exe
          path: unpacker.exe
